parameters:
    fonts:
        851ShouXieZaZiTi: "851ShouXieZaZiTi.ttf"
        Alibaba-PuHuiTi-Light: "Alibaba-PuHuiTi-Light.ttf"
        Alibaba-PuHuiTi-Regular: "Alibaba-PuHuiTi-Regular.ttf"
        Alibaba-PuHuiTi-Medium: "Alibaba-PuHuiTi-Medium.ttf"
        Alibaba-PuHuiTi-Bold: "Alibaba-PuHuiTi-Bold.ttf"
        Alibaba-PuHuiTi-Heavy: "Alibaba-PuHuiTi-Heavy.ttf"
        BaoTuXiaoBaiTi: "BaoTuXiaoBaiTi.ttf"
        ChaoJiXi: "ChaoJiXi.ttf"
        GenJyuuGothicL-ExtraLight: "GenJyuuGothicL-ExtraLight.ttf"
        GenJyuuGothicL-Light: "GenJyuuGothicL-Light.ttf"
        GenJyuuGothicL-Medium: "GenJyuuGothicL-Medium.ttf"
        GenJyuuGothicL-Normal: "GenJyuuGothicL-Normal.ttf"
        GenJyuuGothicL-Regular: "GenJyuuGothicL-Regular.ttf"
        GenJyuuGothicL-Bold: "GenJyuuGothicL-Bold.ttf"
        GenJyuuGothicL-Heavy: "GenJyuuGothicL-Heavy.ttf"
        GenJyuuGothicL-Monospace-ExtraLight: "GenJyuuGothicL-Monospace-ExtraLight.ttf"
        GenJyuuGothicL-Monospace-Light: "GenJyuuGothicL-Monospace-Light.ttf"
        GenJyuuGothicL-Monospace-Normal: "GenJyuuGothicL-Monospace-Normal.ttf"
        GenJyuuGothicL-Monospace-Regular: "GenJyuuGothicL-Monospace-Regular.ttf"
        GenJyuuGothicL-Monospace-Medium: "GenJyuuGothicL-Monospace-Medium.ttf"
        GenJyuuGothicL-Monospace-Bold: "GenJyuuGothicL-Monospace-Bold.ttf"
        GenJyuuGothicL-Monospace-Heavy: "GenJyuuGothicL-Monospace-Heavy.ttf"
        GenRyuMinTW-ExtraLight: "GenRyuMinTW-ExtraLight.ttf"
        GenRyuMinTW-Light: "GenRyuMinTW-Light.ttf"
        GenRyuMinTW-Regular: "GenRyuMinTW-Regular.ttf"
        GenRyuMinTW-Medium: "GenRyuMinTW-Medium.ttf"
        GenRyuMinTW-SemiBold: "GenRyuMinTW-SemiBold.ttf"
        GenRyuMinTW-Bold: "GenRyuMinTW-Bold.ttf"
        GenRyuMinTW-Heavy: "GenRyuMinTW-Heavy.ttf"
        GenShinGothic-ExtraLight: "GenShinGothic-ExtraLight.ttf"
        GenShinGothic-Light: "GenShinGothic-Light.ttf"
        GenShinGothic-Normal: "GenShinGothic-Normal.ttf"
        GenShinGothic-Regular: "GenShinGothic-Regular.ttf"
        GenShinGothic-Medium: "GenShinGothic-Medium.ttf"
        GenShinGothic-Bold: "GenShinGothic-Bold.ttf"
        GenShinGothic-Heavy: "GenShinGothic-Heavy.ttf"
        GenShinGothic-Monospace-ExtraLight: "GenShinGothic-Monospace-ExtraLight.ttf"
        GenShinGothic-Monospace-Light: "GenShinGothic-Monospace-Light.ttf"
        GenShinGothic-Monospace-Normal: "GenShinGothic-Monospace-Normal.ttf"
        GenShinGothic-Monospace-Regular: "GenShinGothic-Monospace-Regular.ttf"
        GenShinGothic-Monospace-Medium: "GenShinGothic-Monospace-Medium.ttf"
        GenShinGothic-Monospace-Bold: "GenShinGothic-Monospace-Bold.ttf"
        GenShinGothic-Monospace-Heavy: "GenShinGothic-Monospace-Heavy.ttf"
        HuXiaoBoNanShenTi: "HuXiaoBoNanShenTi.otf"
        HuXiaoBoSaoBaoTi: "HuXiaoBoSaoBaoTi.otf"
        HuXiaoBoZhenShuaiTi: "HuXiaoBoZhenShuaiTi.otf"
        OPPOSans-L: "OPPOSans-L.ttf"
        OPPOSans-R: "OPPOSans-R.ttf"
        OPPOSans-M: "OPPOSans-M.ttf"
        OPPOSans-B: "OPPOSans-B.ttf"
        OPPOSans-H: "OPPOSans-H.ttf"
        PangMenZhengDaoBiaoTiTi: "PangMenZhengDaoBiaoTiTi.ttf"
        PangMenZhengDaoCuShuTi: "PangMenZhengDaoCuShuTi.ttf"
        PangMenZhengDaoQingSongTi: "PangMenZhengDaoQingSongTi.otf"
        RuiZiZhenYanTi: "RuiZiZhenYanTi.ttf"
        SourceHanSansCN-ExtraLight: "SourceHanSansCN-ExtraLight.otf"
        SourceHanSansCN-Light: "SourceHanSansCN-Light.otf"
        SourceHanSansCN-Normal: "SourceHanSansCN-Normal.otf"
        SourceHanSansCN-Regular: "SourceHanSansCN-Regular.otf"
        SourceHanSansCN-Medium: "SourceHanSansCN-Medium.otf"
        SourceHanSansCN-Bold: "SourceHanSansCN-Bold.otf"
        SourceHanSansCN-Heavy: "SourceHanSansCN-Heavy.otf"
        SourceHanSerifCN-ExtraLight: "SourceHanSerifCN-ExtraLight.ttf"
        SourceHanSerifCN-Light: "SourceHanSerifCN-Light.ttf"
        SourceHanSerifCN-Regular: "SourceHanSerifCN-Regular.ttf"
        SourceHanSerifCN-Medium: "SourceHanSerifCN-Medium.ttf"
        SourceHanSerifCN-SemiBold: "SourceHanSerifCN-SemiBold.ttf"
        SourceHanSerifCN-Bold: "SourceHanSerifCN-Bold.ttf"
        SourceHanSerifCN-Heavy: "SourceHanSerifCN-Heavy.ttf"
        YangRenDongZhuShiTi-Extralight: "YangRenDongZhuShiTi-Extralight.ttf"
        YangRenDongZhuShiTi-Light: "YangRenDongZhuShiTi-Light.ttf"
        YangRenDongZhuShiTi-Regular: "YangRenDongZhuShiTi-Regular.ttf"
        YangRenDongZhuShiTi-Medium: "YangRenDongZhuShiTi-Medium.ttf"
        YangRenDongZhuShiTi-SemiBold: "YangRenDongZhuShiTi-SemiBold.ttf"
        YangRenDongZhuShiTi-Bold: "YangRenDongZhuShiTi-Bold.ttf"
        YangRenDongZhuShiTi-Heavy: "YangRenDongZhuShiTi-Heavy.ttf"
        YouSheBiaoTiHei: "YouSheBiaoTiHei.ttf"
        YuanJieMingChaoTi: "YuanJieMingChaoTi.ttf"
        ZCOOLCangErYuYangTi-Light: "ZCOOLCangErYuYangTi-Light.ttf"
        ZCOOLCangErYuYangTi-Regular: "ZCOOLCangErYuYangTi-Regular.ttf"
        ZCOOLCangErYuYangTi-Medium: "ZCOOLCangErYuYangTi-Medium.ttf"
        ZCOOLCangErYuYangTi-Bold: "ZCOOLCangErYuYangTi-Bold.ttf"
        ZCOOLCangErYuYangTi-Heavy: "ZCOOLCangErYuYangTi-Heavy.ttf"
        ZCOOLGaoDuanHei: "ZCOOLGaoDuanHei.ttf"
        ZCOOLKuaiLeTi: "ZCOOLKuaiLeTi.ttf"
        ZCOOLWenYiTi: "ZCOOLWenYiTi.ttf"
        ZCOOLXiaoWeiLogoTi: "ZCOOLXiaoWeiLogoTi.otf"
        ZhuangJiaMingChao: "ZhuangJiaMingChao.ttf"
